### ISSUE TITLE
Api Generator nicht sichtbar SQLDev oddgen

### ISSUE THREAD

**Issue by pettinger** [OraMUC/table-api-generator#1]
Hallo Ottmar,
nach der tollen Vorstellung beim Meetup in Frankfurt habe ich die Bereitstellung auf GITHub sehnsüchtig erwartet. Heute Morgen auch gleich ausprobiert. Leider findet der ODDGen im SQLDev den TAPI Genearator nicht immer. 
Das Szenario: 
TAPI Generator ist im Schema A (einem Tools Schema) installiert
Grant Execute grant execute on OM_TAPIGEN_ODDGEN_WRAPPER to public;
grant execute on OM_TAPIGEN to public;
Im Schema A wird der Generator auch korrekt im SQLDev angezeigt
Aber im Schema B, dem Applikationsschema, keine Spur vom Generator

Eine Idee, was ich vergessen habe?

Gruß
Peter

**Comment by ogobrecht** [comment]
Hallo Peter,

Du hast nichts vergessen, wenn es komplizierter wäre, dann hätte ich es in der README dokumentiert. Bei mir funktioniert es allein mit dem grant execute to public auf beide Packages.

Bitte versuche zuerst einmal wie beschrieben in Deinem Applikationsschema mögliche Namenskonflikte zu finden, in dem Du diese Query absetzt:

``` sql
SELECT * FROM TABLE(your_install_schema.om_tapigen.view_naming_conflicts); 
```

Wenn das soweit funktioniert, dann hast Du kein Berechtigungsproblem. Ansonsten solltest Du Deine Grants noch einmal wiederholen. 

Wenn dann die Query geht, es aber immer noch im SQL-Developer hängt, empfehle ich zuerst einmal über den Upgrademechanismus die oddgen Extension zu aktualisieren - hier ist in den letzten Tagen(Wochen) wohl einiges passiert. Danach einmal sauber den SQL Developer durchstarten und dann sollte es eigentlich hier auch gehen. Welche SQL Developer Version nutzt Du eigentlich? Ich habe die 4.1.3 im Einsatz. 

Ich hoffe, ich konnte Dir ein wenig helfen. Laß von Dir hören - auch wenn es funktioniert. Dann kann ich das Ticket schließen. 

Viel Glück und beste Grüße
Ottmar

**Comment by pettinger** [comment]
Vielen Dank für die schnelle Rückmeldung. Ja, die veraltete Version des oddgen package war die Ursache. Hatte es zwar erst von 14 Tagen installiert,  aber nach dem Updaten "klappts auch mit dem Nachbarn". Ich schau mal, ob ich den TAPI Generator auch für unser "suboptimales" DB Design verwenden kann. 
Grüße aus dem Taunus
Peter

**Comment by ogobrecht** [comment]
Hallo Peter,

das freut mich. Danke für die Rückmeldung. Feedback und Anregungen jeder Art sind stets willkommen :-)

Beste Grüße
Ottmar
