### ISSUE TITLE
Support of multiple column PKs

### ISSUE THREAD

**Issue by pettinger** [OraMUC/table-api-generator#10]
Hi Ottmar,
i still lack the capability to generate an api for tables with a pk consisting of multiple columns. is there a chance this feature will be implemented?

Peter

**Comment by ogobrecht** [comment]
Hi Peter,

yes, we will try it the next weeks and keep you informed.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Peter,

it took a long time but now you can start to test your tables with multi column primary keys ;-)

Please check out the `0.5` branch, start testing and let us know if it is working for you. Please keep in mind, that the code is still in beta - do not use it in production. Please have also a look at the README sections **To Do** and **Done** - there was a lot ongoing.

Attention: The SQL Developer integration is currently missing/not working, documentation is unfinished and the example-api.md is not updated yet.

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Peter,

the new version 0.5.0 is out. It supports now multi column primary keys as requested. Therefore I close now this issue.

Please let us know, if you have any further questions.

Best regards
Ottmar
