### ISSUE TITLE
new Parameters p_enable_col_camel and p_enable_prefic_fnc_prc

### ISSUE THREAD

**Issue by amseltech1** [OraMUC/table-api-generator#23]
Hello, 
I like the table-api-generator. 
I added 2 new parameters:
1. **p_enable_col_camel**: we never user camelcase column names and i don't like the reading of all the double quotes. I added the parameter for generating the api whitout double quotes. 

1. **p_enable_prefix_fnc_prc** is a parameter that concatinate a prefix fnc_ for all functions and a prefix prc_ fro all procedures in the tapi

Thank's

**Comment by ogobrecht** [comment]
Hi,

the new version of the generator is out. You can now configure it to not have the double quotes (p_double_quote_names, default is true).

Your second point is not implemented, sorry. Modern IDEs are showing via a symbol if it is a function or a procedure. And the usage is transparent - if you assign the return value to a variable the function is used and without the assignment the procedure is called by the PL/SQL engine. In both cases you can use the same name e.g. `create_row`. To reflect the method type in the methods name is not very useful here.

Best regards
Ottmar
