### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wethw00** [OraMUC/table-api-generator#35]
Hello,

OWNER
--------------------------------------------------------------------------------
NAME
--------------------------------------------------------------------------------
TYPE                  SEQUENCE       LINE   POSITION
------------------- ---------- ---------- ----------
TEXT
--------------------------------------------------------------------------------
ATTRIBUTE MESSAGE_NUMBER
--------- --------------
OM
OM_TAPIGEN
PACKAGE BODY                 1        483         32
PLS-00201: identifier 'V' must be declared
ERROR                201

OM
OM_TAPIGEN
PACKAGE BODY                 2        483          5
PL/SQL: Statement ignored
ERROR                  0

This is what I get as I run the install.sql on Oracle 19.3 ( win 64 bit ) whitout apex  . . . . ..  .

User I install is OM granted DBA rights . . . . .   ( I guess that's enough ? )

**Comment by ogobrecht** [comment]
Hi,

our table API generator has no dependency on Oracle APEX. And you need no DBA rights. A normal user which can create packages and tables should be enough.

Can you please tell us, which version you try to install? And in which tool do you run the install script? SQL*Plus, SQLcl, SQL Developer...

You can also try to install our new version in the development branch (we are short before a new release and I use it already in projects). For this, you have to select the branch under the code tab in GitHub and download it. Then run the om_tapigen_install.sql script.

Best regards
Ottmar

**Comment by wethw00** [comment]
Hello all,

I try-ed to install it in / from sql/plus . . . . .

**Comment by wethw00** [comment]
Dear Ottmar

I try-ed to follow the install manual from version 0.5.2 . . . . . 

I have SQL*PLUS and Oracle PL/SQL Developer  But that show sometimes some dutch language . . . . .

**Comment by wethw00** [comment]
So I run the install.sql script . . . . 

Kind regards
Hopes it helps
                           Wouter

**Comment by wethw00** [comment]
SQL> connect om
Enter password:
Connected.
SQL> @ om_tapigen_install.sql

Install github.com/OraMUC/table-api-generator
============================================================
Set compiler flags
Compile package om_tapigen (spec)
No errors.
Compile package om_tapigen (body)
No errors.
Compile package om_tapigen_oddgen wrapper (spec)
No errors.
Compile package om_tapigen_oddgen wrapper (body)
No errors.
============================================================
Installation Done

Don't forget to create a private or public synonym,
if you installed in a central tools schema. Also see
https://github.com/OraMUC/table-api-generator/blob/master/docs/getting-started.md


Yoepie / Happy

Wouter

**Comment by ogobrecht** [comment]
Hi Wouter,

thanks for the feedback. As I understand it right you were able to install the table API generator. Please note that I released some minutes ago the new version 0.6.0 of the generator. So you can use directly the master branch now.

Best regards
Ottmar
