### ISSUE TITLE
Add example of generated API to documentation

### ISSUE THREAD

**Issue by jgebal** [OraMUC/table-api-generator#4]
It would be great to provide an example of the API generated using the generator into the documentation.
Without that, I need to download, install and run it to see what it actually does and if it is what I need.

A simple hr.departments table from [oracle examples](https://github.com/oracle/db-sample-schemas) would be god enough.

**Comment by aborngra** [comment]
The generated code you mean? OK, we will provide it somehow within the README.
Thanks!

**Comment by ogobrecht** [comment]
Hi Jacek,

I added an [example API](https://github.com/OraMUC/table-api-generator/blob/master/example-api.md) - on the table HR.EMPLOYEES because this table has an unique key and therefore we get a `get_pk_by_unique_cols` function.

Best regards
Ottmar
