### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by rtpguru101** [OraMUC/table-api-generator#45]
Is there any reason why there is no exception handling in this entire template ?

**Comment by ogobrecht** [comment]
We discussed this in the past, but we cannot decide for the developer, what should be done in the case of errors.

The first thing which will come to mind is logging, but which logging method/framework? We don't know what the developers are using for logging.

The second thing is, that the generated table APIs are very generic. You can use them to separate the data schema from the business logic schema. In more complex applications and/or data models we would expect that on top of these generic APIs developers build business APIs which are transaction save (the table APIs itself do not commit). In such business APIs (also called BAPI or XAPI) the developers are free to use a logging framework of their choice and do the exception handling depending on their needs.

Hopefully this answers your question.

Best regards
Ottmar

**Comment by rtpguru101** [comment]
thank you and that helps
