### ISSUE TITLE
Oracle 23c Free - Install-Script returns ORA-01422

### ISSUE THREAD

**Issue by scl-4711** [OraMUC/table-api-generator#47]
The install script "om_tapigen_install.sql" shows "_ORA-01422 exact fetch returns more_"

Cause: 
![image](https://user-images.githubusercontent.com/12970066/230380202-9b317871-ab82-451e-854f-9d732df649f2.png)

Very interesting - happy easter to you ;-)

**Comment by ogobrecht** [comment]
Hi Steffen,

thank you for reporting this. Will have a look soon.

Happy easter to you also ;-)

**Comment by ogobrecht** [comment]
Hi Steffen,

I corrected the install script accordingly (v0.6.2). The fix is very minimal - sorry, that this took so long - I needed to find only time to look at it.

Thanks again for report the issue. Best regards
Ottmar

**Comment by scl-4711** [comment]
Hi Ottmar,

you fixed it at line 12 - but not at line 21...

Best regars
Steffen
