### ISSUE TITLE
Specifying shorter table name substitution variables in p_one_to_one_view_name generates corrupted view name

### ISSUE THREAD

**Issue by softinn72** [OraMUC/table-api-generator#50]
Hi Ottmar,
I found a small issue in the usage of shorter table name substitution variables in **p_one_to_one_view_name** parameter, where when we specify for example a substitution like '#TABLE_NAME_20#_V', the generated view name is corrupted (that is we get only the first character of the table name followed by the trailing string, like X_V), while if we use #TABLE_NAME#_V, the expected view name is generated correctly.

Thanks,
Paolo Marzucco

**Comment by ogobrecht** [comment]
Hi Paolo,

I will look into it. Sounds like a bug...
