### ISSUE TITLE
P%COLUMN_MAPPING parameters are case sensitive

### ISSUE THREAD

**Issue by softinn72** [OraMUC/table-api-generator#51]
Hi Ottmar,
I am not sure if this is a real bug or not, but it bit me when I started testing the latest version and I could not understand why the parameter I just populated was not working. In summary I noticed that if I pass for example the following to the table generator:
```
p_row_version_column_mapping => 'Version_id=global_version_sequence.nextval'
```
it will not consider the parameter without raising any error, because the column name is not all uppercase. This behaviour affects all the column mapping parameters.

It's true that the example in the documentation shows the column name in uppercase, but if I specify for example a non existing column name, then no error is raised. Wouldn't it be more user friendly to raise an error if the specified column name is not found in the table definition, instead of failing silently?

Thanks,
Paolo

**Comment by ogobrecht** [comment]
Hi Paolo,

sorry for my late response. I will have a look into it. In general I think your are right - the generator should raise an error when  a specified column does not exist. I will keep you updated...

Best regards
Ottmar
