### ISSUE TITLE
Error installing on oracle 23c free

### ISSUE THREAD

**Issue by ljvankempen** [OraMUC/table-api-generator#52]
Hello
During installing I got the error:

SQL> @om_tapigen_install

Install github.com/OraMUC/table-api-generator
============================================================
Set compiler flags
declare
*
ERROR at line 1:
ORA-01422: exact fetch returned more than the requested number of rows
ORA-06512: at line 12

I have fixed this with  execute immediate q'[
      select replace(regexp_substr(min(version_full), '\d+\.\d+'), '.', null) as db_version
        from product_component_version
       where product like 'Oracle Database%' ]'

( min function)

Maybe not the way to do it but it works.

Leon

**Comment by maahelal** [comment]
similar work-around, I added "distinct" before replace

**Comment by ogobrecht** [comment]
Hi Leon,

I thought I have fixed this (was reported already by another user). But I missed the second occurence of the same issue. Sorry for this and thank you for reporting it. Will have a look at your other reported issue also.

Best regards
Ottmar
