### ISSUE TITLE
Generating default values for virtual columns

### ISSUE THREAD

**Issue by ljvankempen** [OraMUC/table-api-generator#53]
Hi
The system is generating default values for virtual columns.
II have created a workaround as follows:

 FUNCTION list_rowcols_w_dict_defaults RETURN t_tab_list IS
      v_result           t_tab_list;
      v_list_padding     t_vc2_30;
      v_index            PLS_INTEGER;
      v_operator_padding PLS_INTEGER;
    BEGIN
      v_list_padding     := get_list_padding(4);
      v_operator_padding := get_operator_padding;
      FOR i IN 1 .. g_columns.count
      LOOP
        IF g_columns(i).data_default IS NOT NULL
            AND g_columns(i).is_hidden_yn = 'N'
            **_AND g_columns(i).is_virtual_yn = 'N' ---- ADJUSTMENT LVK_**

**Comment by ogobrecht** [comment]
Hi Leon,

thank you for reporting this - will take a look and fix it.

Best regards
Ottmar
