### ISSUE TITLE
More control over package names

### ISSUE THREAD

**Issue by jgebal** [OraMUC/table-api-generator#8]
It would be great to be able to define a pattern/name for generated API .
That way any project could make the API conform to their naming standards/requirements.
In my case I'd like those to be named `u3_api_#table_name#`. It would be great if name would be parameter-driven.

**Comment by ogobrecht** [comment]
Hi Jacek,

as you mentioned before - with good default values for new parameters I see no reason to not to have this parameterized. could be the same like with our `p_sequence_name` parameter, which also do a replacement for the given string:

<img width="911" alt="p_sequence_name" src="https://cloud.githubusercontent.com/assets/10425445/26529010/0e72f7f2-43b8-11e7-99c3-cf5cb9a6bbd3.png">

Suggested parameter name: `p_api_name varchar2 default null`

Best regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Jacek,

Additional idea: the current string replacements are driven by our existing internal table and column name short names. I could think of to grab the number inside with an regex and you as a user are free to set any number you like as long as you use `#TABLE_NAME_XX#` or `#PK_COLUMN_XX#`.

As an example: you could use then `#TABLE_NAME_17#`.

The `#COLUMN_PREFIX#` is derived automatically - in the example below the it would be `EMP`. If not all columns have the same prefix then it would be null.

```sql
CREATE TABLE "HR"."EMPLOYEES" (
    "EMP_ID"               NUMBER(6,0),
    "EMP_FIRST_NAME"       VARCHAR2(20 BYTE),
    "EMP_LAST_NAME"        VARCHAR2(25 BYTE),
    "EMP_EMAIL"            VARCHAR2(25 BYTE),
    "EMP_PHONE_NUMBER"     VARCHAR2(20 BYTE),
    "EMP_HIRE_DATE"        DATE,
    "EMP_JOB_ID"           VARCHAR2(10 BYTE),
    "EMP_SALARY"           NUMBER(8,2),
    "EMP_COMMISSION_PCT"   NUMBER(2,2),
    "EMP_MANAGER_ID"       NUMBER(6,0),
    "EMP_DEPARTMENT_ID"    NUMBER(4,0)
);
```

Best regards
Ottmar

**Comment by ogobrecht** [comment]
I forgot to tell you why we do this at all:

We need this for the SQL Developer integration - there you can select multiple tables and generate all API code at ones - so we need a way to define a variable sequence name for each selected table.

Regards
Ottmar

**Comment by ogobrecht** [comment]
Hi Jacek,

the new version 0.5.0 is out (it took a long time). You can define in this version a custom API name - therefore I close now this issue.

Best regards
Ottmar
